reinforcement_break_counter: 20 # How many times does a reinforced block need to be broken? (Per reinforcement level)
reinforcement_explosion_strength: 8 # How many "breaks" should an explosion incur on the reinforced block? Strength lowers as explosion gets farther. 
reinforcement_blocks_can_burn: false # Can reinforced blocks burn? If enabled, fire will take x times longer to break a block (x = reinforcement_break_counter)
reinforcement_block: OBSIDIAN # What block is used to reinforce another? Refer to: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
reinforcement_block_drop_chance: 40 # Chance of dropping [reinforcement_block] when a reinforced block is destroyed (in percent)
reinforcement_not_reinforceable: # What blocks cannot be reinforced? Refer to: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  - BEDROCK
  - ENDER_PORTAL_FRAME
  - TALL_GRASS
  - GRASS
  - BAMBOO
  - FLOWER
  - MUSHROOM
  - DEAD_BUSH
  - SUGAR_CANE
  - VINE
  - NETHER_WART
  - STEM
  - SAPLING
  - BARRIER
  - BEETROOT
  - BANNER
  - CARPET
  - BRAIN_CORAL
  - CHORUS_FLOWER
  - COMMAND_BLOCK 
  - MOVING_PISTON
  - PISTON_HEAD
  - TNT
  - FIRE
  - SNOW
  - ICE
  - CACTUS
  - PORTAL
  - CAKE_BLOCK
  - ENDER_PORTAL
  - ROSE
  - SUNFLOWER
  - ORCHID
  - CAMPFIRE
  - DANDELION
  - RAIL
  - KELP
  - CRYSTAL
  - GATEWAY
  - PORTAL
  - END_ROD
  - FERN
  - GLASS_PANE
  - PRESSURE_PLATE
  - IRON_BARS
  - TRAPDOOR
  - LADDER
  - LILAC
  - LILY
  - TULIP
  - BLUET
  - POPPY
  - POTTED
  - ALLIUM
  - REDSTONE
  - SCAFFOLDING
  - BERRY
  - BERRIES
  - TORCH
  - HEAD
  - WALL
  - DOOR
  - AIR